version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./medical_ai.db:/app/medical_ai.db
    environment:
      - DATABASE_URL=sqlite:///./medical_ai.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:8000/api

  # Development service (optional)
  backend-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app/backend
      - ./uploads:/app/uploads
      - ./medical_ai.db:/app/medical_ai.db
    environment:
      - DATABASE_URL=sqlite:///./medical_ai.db
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    profiles:
      - dev

  frontend-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend-dev
    environment:
      - VITE_API_URL=http://localhost:8001/api
    command: ["npm", "run", "dev"]
    profiles:
      - dev 